version: "3.8"

services:
  # Next.js App
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - JWT_SECRET=${JWT_SECRET}
      - NODE_ENV=development
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    command: npm run dev
    depends_on:
      - postgres

  # PostgreSQL Database (Optional - 如果不使用 Neon Cloud)
  postgres:
    image: postgres:16-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=universal
      - POSTGRES_PASSWORD=universal_password
      - POSTGRES_DB=universal_db
    volumes:
      - postgres_data:/ var/lib/postgresql/data

volumes:
  postgres_data:
