name = "nextjs-universal-template"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

# 注意：本项目使用 tRPC 和数据库，不适合 Cloudflare Pages 的纯静态模式
# 推荐使用 Vercel 部署以获得完整功能支持
#
# 如需部署到 Cloudflare，建议使用 @cloudflare/next-on-pages 适配器
# 参考：https://developers.cloudflare.com/pages/framework-guides/nextjs/

# Production environment
[env.production]
vars = { CF_PAGES = "1", NODE_ENV = "production" }

# Preview environment
[env.preview]
vars = { CF_PAGES = "1", ENVIRONMENT = "preview", NODE_ENV = "production" }

