name = "nextjs-universal-template"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

# Cloudflare Pages 配置
# 使用 @cloudflare/next-on-pages 构建时的输出目录
pages_build_output_dir = ".vercel/output/static"

# 注意：@cloudflare/next-on-pages 已废弃，但仍可使用
# 未来建议迁移到 OpenNext: https://opennext.js.org/cloudflare
# 或直接使用 Vercel（零配置，完整支持）

# Production environment
[env.production]
vars = { CF_PAGES = "1", NODE_ENV = "production" }

# Preview environment
[env.preview]
vars = { CF_PAGES = "1", ENVIRONMENT = "preview", NODE_ENV = "production" }

